"""
Django settings for qbtest project.

Generated by 'django-admin startproject' using Django 2.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'f60pg!33oh@(ail8!)0(+rodxfha5uzwy1hu43mn$knvkfz+%='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    
    'testmodel',
    'django_quickbooks',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'qbtest.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'qbtest.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'

QBWC_SETTINGS = {
    'QUEUE_MANAGER_CLASS': 'django_quickbooks.queue_manager.RedisManager',
    'REDIS_DEFAULT_HOST': 'localhost',
    'REDIS_DEFAULT_PORT': 6379,
    'REDIS_DEFAULT_DB': 0,
    'REDIS_DEFAULT_PASSWORD': None,
    'APP_URL': 'http://localhost:8000/qwc/quickbooks-desktop',
    'APP_SUPPORT': 'http://localhost:8000/qwc/quickbooks-desktop/support',
    'APP_ID': '',
    'APP_NAME': 'qbtest',
    # 'APP_DESCRIPTION': "YOUR_APP_DESCRIPTION",
    'OWNER_ID': '55a9fd50-79e9-44e4-8fef-98411c2e8785',
    # 'LOCAL_MODEL_CLASSES': {
    # # This is a pointing to my Customer Model in my app, replace with your own
    #     'Invoice': '',
    #     'Customer': '',
    #     'CustomerPOS': 'Inventory.models.Customer',  
    #     'ItemInventoryPOS': 'Inventory.models.Level7',
    #     'VoucherPOS': 'Inventory.models.OrderVoucher',
    #     'VendorPOS': 'Inventory.models.QBVendor',
    #     'SalesReceiptPOS': 'Inventory.models.OrderReceipt',
    # },
    # if you want to handle Responses in some custom way you can inherit from the ResponseProcessor and point to it in this tuple
  
    # same as above but this is for POS (only in my fork)
   
    'TASKS_PER_REQUEST_LIMIT': 200, #only in my fork
}